window.LENDUP_TRANSLATIONS = {
  es: {
    a11y: { skip: "Saltar al contenido principal" },
    lang: { toggle: "Cambiar idioma", switchToEnglish: "Cambiar idioma a inglés", switchToSpanish: "Cambiar idioma a español" },
    nav: { label: "Navegación principal", open: "Abrir menú", close: "Cerrar menú", home: "Inicio", benefits: "Beneficios", how: "Cómo funciona", safety: "Seguridad", about: "Nosotros", faq: "FAQ" },
    actions: { explore: "Buscar objetos", publish: "Publicar un objeto" },
    status: { available: "Disponible" },
    hero: {
      carouselLabel: "Propuestas principales de LendUp", slide1Label: "1 de 3: propuesta general", slide2Label: "2 de 3: para prestatarios", slide3Label: "3 de 3: para prestamistas",
      previous: "Mostrar slide anterior", next: "Mostrar slide siguiente", indicators: "Seleccionar slide", goTo1: "Ir al slide 1", goTo2: "Ir al slide 2", goTo3: "Ir al slide 3",
      slide1Eyebrow: "Préstamos entre estudiantes universitarios", slide1Title: "Presta lo que no usas.<br><span>Consigue lo que necesitas.</span>", slide1Text: "Encuentra y presta objetos dentro de tu comunidad universitaria, con estudiantes verificados, condiciones claras y respaldo durante todo el préstamo.",
      slide2Eyebrow: "Para quienes necesitan un objeto", slide2Title: "Consigue lo que necesitas sin comprarlo para usarlo una sola vez.", slide2Text: "Busca objetos disponibles, revisa sus condiciones y solicita el periodo que necesitas dentro de tu comunidad universitaria.",
      slide3Eyebrow: "Para quienes tienen algo que prestar", slide3Title: "Dale utilidad a los objetos que hoy permanecen guardados.", slide3Text: "Publica tus objetos, define su disponibilidad y condiciones, revisa solicitudes y gestiona cada préstamo desde la entrega hasta la devolución.",
      trustLabel: "Señales de confianza", trust1: "Estudiantes verificados", trust2: "Condiciones registradas", trust3: "Evidencias del objeto",
      visual1Label: "Vista previa del catálogo de LendUp", visual2Label: "Objetos disponibles en LendUp", visual3Label: "Vista previa de publicación de un objeto", search: "Buscar objetos", verified: "Estudiante verificado", visibleReputation: "Reputación visible", recordedTerms: "Condiciones registradas",
      newListing: "Nueva publicación", defineDetails: "Define los detalles del objeto", availability: "Disponibilidad", fee: "Tarifa", deposit: "Garantía", conditions: "Condiciones", youDecide: "Tú decides cuándo", youDefine: "Definida por ti", recorded: "Queda registrada", clearBefore: "Claras antes de aceptar", readyToPublish: "Listo para publicar"
    },
    benefits: {
      eyebrow: "¿Por qué LendUp?", title: "Todo lo que necesitas para prestar con más confianza", subtitle: "LendUp organiza procesos que normalmente se coordinan de manera informal mediante chats o grupos universitarios.", sliderLabel: "Beneficios de LendUp", controlsLabel: "Seleccionar beneficio",
      card1Title: "Encuentra lo que necesitas", card1Text: "Busca objetos y revisa disponibilidad, ubicación y condiciones antes de enviar una solicitud.",
      card2Title: "Conoce con quién operas", card2Text: "Consulta perfiles, condición de estudiante y reputación antes de concretar un préstamo.",
      card3Title: "Condiciones claras", card3Text: "Tarifa, garantía, fechas y condiciones de la operación quedan registradas para cada reserva.",
      card4Title: "Respaldo durante el préstamo", card4Text: "Evidencias, notificaciones, recordatorios e incidencias acompañan la operación desde la reserva hasta la devolución."
    },
    roles: {
      eyebrow: "Dos formas de participar", title: "Encuentra tu lugar en la comunidad LendUp",
      borrowerEyebrow: "Necesito un objeto", borrowerTitle: "Encuentra lo que necesitas temporalmente.", borrowerText: "Busca por categoría, revisa disponibilidad y condiciones, envía una solicitud y coordina la entrega. Al terminar, devuelve el objeto según lo acordado.", borrowerPoint1: "Búsqueda y disponibilidad", borrowerPoint2: "Solicitud y entrega", borrowerPoint3: "Devolución registrada",
      lenderEyebrow: "Tengo algo para prestar", lenderTitle: "Dale utilidad a los objetos que no estás usando.", lenderText: "Publica el objeto, define disponibilidad y condiciones, revisa solicitudes y coordina la entrega. Confirma la devolución al finalizar el préstamo.", lenderPoint1: "Publicación y condiciones", lenderPoint2: "Solicitudes y entrega", lenderPoint3: "Devolución y reputación"
    },
    catalog: {
      eyebrow: "Explora posibilidades", title: "Objetos para tu vida universitaria", subtitle: "¿Lo necesitas solo por unos días? Quizá otro estudiante ya lo tiene.", cameraCategory: "Cámaras", cameraName: "Cámara Canon", calculatorCategory: "Calculadoras", calculatorName: "Calculadora científica", booksCategory: "Libros", booksName: "Libros académicos", techCategory: "Tecnología", tabletName: "Tablet para estudiar", toolsCategory: "Herramientas", toolsName: "Kit de herramientas", visualRate: "Tarifa definida por el prestamista", demoNote: "Vista demostrativa. La disponibilidad y las condiciones son definidas por cada prestamista."
    },
    how: {
      eyebrow: "Cómo funciona", title: "Un proceso claro para ambos lados", subtitle: "Elige tu rol y conoce cada etapa del préstamo.", tabLabel: "Selecciona tu rol", borrowerTab: "Buscar", lenderTab: "Prestar",
      borrowerSteps: [
        ["Crea y verifica tu cuenta", "Regístrate con tu información universitaria y completa la verificación correspondiente."],
        ["Busca y solicita", "Encuentra el objeto que necesitas, revisa disponibilidad y condiciones, y envía una solicitud."],
        ["Recibe con respaldo", "Completa los pasos de la reserva y registra evidencias al recibir el objeto."],
        ["Devuelve y califica", "Entrega el objeto según lo acordado y registra tu experiencia."]
      ],
      lenderSteps: [
        ["Publica y define condiciones", "Registra el objeto, su disponibilidad, tarifa, garantía y condiciones."],
        ["Revisa solicitudes", "Consulta al estudiante interesado y decide si aceptas la solicitud."],
        ["Entrega con evidencias", "Registra el estado del objeto y confirma la entrega."],
        ["Confirma la devolución", "Revisa el estado final, completa el préstamo y califica al prestatario."]
      ]
    },
    video: { title: "About the Product", text: "Conoce la propuesta y el funcionamiento general de LendUp.", comingSoon: "Video próximamente", iframeTitle: "Video sobre el producto LendUp" },
    safety: {
      eyebrow: "Seguridad y confianza", title: "Confianza en cada etapa del préstamo", subtitle: "LendUp registra información relevante de la operación para que ambas partes tengan mayor claridad antes, durante y después del préstamo.", financialNote: "Tu información financiera sensible no se almacena directamente en LendUp. Las operaciones económicas se procesan mediante un proveedor externo y con los medios que este habilite.",
      item1Title: "Verificación universitaria", item1Text: "Conoce la condición de estudiante antes de operar.", item2Title: "Condiciones registradas", item2Text: "Lo acordado en una reserva permanece registrado para esa operación.", item3Title: "Pagos y garantías", item3Text: "Un proveedor externo procesa tarifa y garantía con sus medios habilitados.", item4Title: "Evidencias del objeto", item4Text: "Las evidencias registran cómo se entrega y cómo se devuelve el objeto.", item5Title: "Gestión de incidencias", item5Text: "Reporta una situación y conserva el contexto de la operación.", item6Title: "Reputación entre estudiantes", item6Text: "Las valoraciones ayudan a tomar mejores decisiones futuras.",
      flowLabel: "Flujo económico de una reserva", flow1: "Se confirma la reserva", flow2: "Se procesa antes de la entrega", flow3: "Se confirma la recepción", flow4: "Se solicita la liberación de la tarifa"
    },
    commission: { eyebrow: "Modelo por operación", title: "Una plataforma que crece con cada préstamo", text1: "LendUp no depende de planes mensuales. Su modelo de negocio se basa en una comisión asociada a las operaciones de préstamo realizadas mediante la plataforma.", text2: "Esto permite que la plataforma acompañe el proceso completo de reserva, entrega, devolución, evidencias, reputación e incidencias." },
    about: { eyebrow: "Sobre nosotros", title: "Construido para la comunidad universitaria", subtitle: "LendUp nace para convertir el préstamo informal de objetos en una experiencia más clara, práctica y respaldada.", missionTitle: "Misión", missionText: "Facilitar el acceso temporal a objetos entre estudiantes universitarios mediante una plataforma que organice cada préstamo de forma clara, práctica y respaldada.", visionTitle: "Visión", visionText: "Impulsar una comunidad universitaria en la que compartir recursos sea una alternativa confiable y habitual frente a comprar objetos que solo se necesitan temporalmente." },
    team: { eyebrow: "Equipo", title: "Las personas detrás de LendUp", role: "Equipo LendUp" },
    faq: {
      eyebrow: "Preguntas frecuentes", title: "Lo importante, explicado con claridad", subtitle: "Respuestas breves sobre publicaciones, reservas, pagos, devoluciones y garantías.",
      items: [
        ["¿Puede cambiar una publicación después de que reservé?", "El prestamista puede modificar su publicación para futuras solicitudes. Sin embargo, cuando una reserva ya fue confirmada, las condiciones registradas para esa operación no cambian debido a modificaciones posteriores de la publicación."],
        ["¿Notificaciones y recordatorios son lo mismo?", "No. Las notificaciones informan sobre eventos que ya ocurrieron, como una solicitud recibida, una aceptación o un pago confirmado. Los recordatorios se envían antes de una fecha o acción programada, como una entrega o devolución próxima."],
        ["¿Cómo se procesan los pagos y garantías?", "Las operaciones económicas son procesadas mediante un proveedor externo. LendUp registra la información necesaria sobre la transacción, pero no almacena directamente la información financiera sensible completa del usuario."],
        ["¿Cuándo recibe el prestamista la tarifa?", "Cuando corresponda una tarifa, el prestatario la procesa después de confirmarse la reserva y antes de la entrega. La liberación al prestamista se solicita después de que el prestatario confirma que recibió el objeto y el préstamo queda activo."],
        ["¿Puedo cancelar una reserva?", "Una reserva puede cancelarse antes de la confirmación de recepción del objeto. Una vez confirmado que el objeto fue recibido y el préstamo está activo, la operación ya no se cancela; corresponde gestionar una devolución."],
        ["¿Puedo devolver un objeto antes?", "Sí. La devolución anticipada debe seguir el mismo proceso de evidencias y confirmación de recepción por parte del prestamista."],
        ["¿Recibo un reembolso si devuelvo antes?", "La devolución anticipada no genera automáticamente un reembolso proporcional de la tarifa. Una incidencia y su resolución podrían determinar un tratamiento diferente cuando corresponda."],
        ["¿Qué ocurre con la garantía si devuelvo antes?", "La garantía sigue el proceso normal de devolución cuando el prestamista confirma la recepción del objeto y no existen incidencias pendientes."]
      ]
    },
    cta: { eyebrow: "Comunidad LendUp", title: "Tu próximo préstamo puede empezar aquí.", text: "Encuentra lo que necesitas o dale utilidad a aquello que no estás usando dentro de tu comunidad universitaria.", publishPrompt: "¿Tienes algo para prestar? Publica un objeto" },
    footer: { tagline: "Presta lo que no usas. Consigue lo que necesitas.", description: "Préstamos temporales de objetos entre estudiantes universitarios, con procesos más claros y respaldados.", explore: "Explora", legal: "Legal", follow: "Síguenos", terms: "Términos y condiciones", privacy: "Política de privacidad", rights: "Todos los derechos reservados." },
    social: { github: "GitHub de LendUp", youtube: "YouTube de LendUp", instagram: "Instagram de LendUp", linkedin: "LinkedIn de LendUp" },
    legal: { back: "Volver al inicio", notice: "Documento general pendiente de revisión legal. Los datos de la entidad responsable, jurisdicción y fechas definitivas deben validarse antes del lanzamiento.", updated: "Versión de referencia: octubre de 2026", termsTitle: "Términos y condiciones", termsIntro: "Estas condiciones describen de forma general el uso de LendUp y las responsabilidades básicas de quienes prestan o solicitan objetos.", privacyTitle: "Política de privacidad", privacyIntro: "Esta política explica, en términos generales, qué información necesita LendUp para operar y cómo se relaciona con los préstamos realizados en la plataforma." },
    notFound: { title: "Esta página no está disponible", text: "El enlace puede haber cambiado o la página ya no existe.", button: "Volver al inicio" }
  },
  en: {
    a11y: { skip: "Skip to main content" },
    lang: { toggle: "Change language", switchToEnglish: "Switch language to English", switchToSpanish: "Switch language to Spanish" },
    nav: { label: "Primary navigation", open: "Open menu", close: "Close menu", home: "Home", benefits: "Benefits", how: "How it works", safety: "Safety", about: "About us", faq: "FAQ" },
    actions: { explore: "Find items", publish: "List an item" },
    status: { available: "Available" },
    hero: {
      carouselLabel: "Main LendUp propositions", slide1Label: "1 of 3: general proposition", slide2Label: "2 of 3: for borrowers", slide3Label: "3 of 3: for lenders", previous: "Show previous slide", next: "Show next slide", indicators: "Select a slide", goTo1: "Go to slide 1", goTo2: "Go to slide 2", goTo3: "Go to slide 3",
      slide1Eyebrow: "Peer-to-peer lending for university students", slide1Title: "Lend what you don't use.<br><span>Get what you need.</span>", slide1Text: "Find and lend items within your university community, with verified students, clear terms, and support throughout every loan.",
      slide2Eyebrow: "For students who need an item", slide2Title: "Get what you need without buying it for one-time use.", slide2Text: "Find available items, review their terms, and request the period you need within your university community.",
      slide3Eyebrow: "For students with something to lend", slide3Title: "Put the items sitting in storage to good use.", slide3Text: "List your items, set their availability and terms, review requests, and manage each loan from handoff to return.",
      trustLabel: "Trust signals", trust1: "Verified students", trust2: "Recorded terms", trust3: "Item evidence", visual1Label: "Preview of the LendUp catalog", visual2Label: "Items available on LendUp", visual3Label: "Preview of an item listing", search: "Search items", verified: "Verified student", visibleReputation: "Visible reputation", recordedTerms: "Recorded terms", newListing: "New listing", defineDetails: "Set the item's details", availability: "Availability", fee: "Fee", deposit: "Deposit", conditions: "Terms", youDecide: "You choose when", youDefine: "Set by you", recorded: "Recorded for the loan", clearBefore: "Clear before accepting", readyToPublish: "Ready to list"
    },
    benefits: {
      eyebrow: "Why LendUp?", title: "Everything you need to lend with greater confidence", subtitle: "LendUp brings structure to processes that are usually coordinated informally through chats or university groups.", sliderLabel: "LendUp benefits", controlsLabel: "Select a benefit",
      card1Title: "Find what you need", card1Text: "Search for items and check availability, location, and terms before sending a request.", card2Title: "Know who you're dealing with", card2Text: "Review profiles, student status, and reputation before arranging a loan.", card3Title: "Clear terms", card3Text: "The fee, deposit, dates, and terms are recorded for each booking.", card4Title: "Support throughout the loan", card4Text: "Evidence, notifications, reminders, and issue management support the process from booking to return."
    },
    roles: {
      eyebrow: "Two ways to take part", title: "Find your place in the LendUp community", borrowerEyebrow: "I need an item", borrowerTitle: "Find what you need temporarily.", borrowerText: "Browse by category, review availability and terms, send a request, and arrange handoff. When you're done, return the item as agreed.", borrowerPoint1: "Search and availability", borrowerPoint2: "Request and handoff", borrowerPoint3: "Recorded return", lenderEyebrow: "I have something to lend", lenderTitle: "Put the items you aren't using to good use.", lenderText: "List the item, set availability and terms, review requests, and arrange handoff. Confirm the return when the loan ends.", lenderPoint1: "Listing and terms", lenderPoint2: "Requests and handoff", lenderPoint3: "Return and reputation"
    },
    catalog: { eyebrow: "Explore the possibilities", title: "Items for university life", subtitle: "Only need it for a few days? Another student may already have it.", cameraCategory: "Cameras", cameraName: "Canon camera", calculatorCategory: "Calculators", calculatorName: "Scientific calculator", booksCategory: "Books", booksName: "Academic books", techCategory: "Technology", tabletName: "Study tablet", toolsCategory: "Tools", toolsName: "Tool kit", visualRate: "Fee set by the lender", demoNote: "Demonstration view. Availability and terms are set by each lender." },
    how: {
      eyebrow: "How it works", title: "A clear process for both sides", subtitle: "Choose your role and see every stage of a loan.", tabLabel: "Select your role", borrowerTab: "Find", lenderTab: "Lend",
      borrowerSteps: [["Create and verify your account", "Register with your university information and complete the relevant verification."], ["Find and request", "Find the item you need, review availability and terms, and send a request."], ["Receive with support", "Complete the booking steps and record evidence when you receive the item."], ["Return and review", "Return the item as agreed and record your experience."]],
      lenderSteps: [["List and set terms", "Record the item, its availability, fee, deposit, and terms."], ["Review requests", "Review the interested student and decide whether to accept the request."], ["Hand off with evidence", "Record the item's condition and confirm the handoff."], ["Confirm the return", "Review the final condition, complete the loan, and review the borrower."]]
    },
    video: { title: "About the Product", text: "Learn about LendUp's proposition and overall experience.", comingSoon: "Video coming soon", iframeTitle: "About the LendUp product" },
    safety: {
      eyebrow: "Safety and trust", title: "Confidence at every stage of the loan", subtitle: "LendUp records relevant transaction details so both parties have greater clarity before, during, and after the loan.", financialNote: "Your sensitive financial information is not stored directly by LendUp. Financial transactions are processed by an external provider using its enabled payment methods.", item1Title: "University verification", item1Text: "Check student status before transacting.", item2Title: "Recorded terms", item2Text: "The terms agreed in a booking remain recorded for that transaction.", item3Title: "Payments and deposits", item3Text: "An external provider processes fees and deposits using its supported methods.", item4Title: "Item evidence", item4Text: "Evidence records the item's condition at handoff and return.", item5Title: "Issue management", item5Text: "Report an issue while preserving the transaction context.", item6Title: "Student reputation", item6Text: "Reviews help the community make better future decisions.", flowLabel: "Booking payment flow", flow1: "The booking is confirmed", flow2: "Payment is processed before handoff", flow3: "Receipt is confirmed", flow4: "Fee release is requested"
    },
    commission: { eyebrow: "Per-transaction model", title: "A platform that grows with every loan", text1: "LendUp does not rely on monthly plans. Its business model is based on a commission associated with loan transactions completed through the platform.", text2: "This allows the platform to support the full booking, handoff, return, evidence, reputation, and issue-management process." },
    about: { eyebrow: "About us", title: "Built for the university community", subtitle: "LendUp was created to turn informal item lending into a clearer, more practical, and better-supported experience.", missionTitle: "Mission", missionText: "Make temporary access to items easier for university students through a platform that organizes every loan in a clear, practical, and supported way.", visionTitle: "Vision", visionText: "Foster a university community where sharing resources is a trusted and everyday alternative to buying items that are only needed temporarily." },
    team: { eyebrow: "Team", title: "The people behind LendUp", role: "LendUp team" },
    faq: {
      eyebrow: "Frequently asked questions", title: "The important details, clearly explained", subtitle: "Short answers about listings, bookings, payments, returns, and deposits.",
      items: [["Can a listing change after I book?", "The lender can update the listing for future requests. However, once a booking is confirmed, the terms recorded for that transaction do not change because of later listing updates."], ["Are notifications and reminders the same?", "No. Notifications report events that have already happened, such as a request, acceptance, or confirmed payment. Reminders are sent before a scheduled date or action, such as an upcoming handoff or return."], ["How are payments and deposits processed?", "Financial transactions are processed by an external provider. LendUp records the required transaction details but does not directly store the user's complete sensitive financial information."], ["When does the lender receive the fee?", "When a fee applies, the borrower processes it after the booking is confirmed and before handoff. Release to the lender is requested after the borrower confirms receipt and the loan becomes active."], ["Can I cancel a booking?", "A booking can be canceled before receipt of the item is confirmed. Once the item has been received and the loan is active, it can no longer be canceled; a return must be managed instead."], ["Can I return an item early?", "Yes. An early return follows the same evidence and receipt-confirmation process by the lender."], ["Do I get a refund if I return early?", "An early return does not automatically generate a proportional fee refund. An issue and its resolution may result in different handling when appropriate."], ["What happens to the deposit if I return early?", "The deposit follows the standard return process once the lender confirms receipt of the item and there are no pending issues."]]
    },
    cta: { eyebrow: "LendUp community", title: "Your next loan can start here.", text: "Find what you need or put the items you aren't using to work within your university community.", publishPrompt: "Have something to lend? List an item" },
    footer: { tagline: "Lend what you don't use. Get what you need.", description: "Temporary item lending between university students, with clearer and better-supported processes.", explore: "Explore", legal: "Legal", follow: "Follow us", terms: "Terms and conditions", privacy: "Privacy policy", rights: "All rights reserved." },
    social: { github: "LendUp on GitHub", youtube: "LendUp on YouTube", instagram: "LendUp on Instagram", linkedin: "LendUp on LinkedIn" },
    legal: { back: "Back to home", notice: "General document pending legal review. The responsible entity, jurisdiction, and final effective dates must be validated before launch.", updated: "Reference version: October 2026", termsTitle: "Terms and conditions", termsIntro: "These terms provide a general description of LendUp usage and the basic responsibilities of people who lend or request items.", privacyTitle: "Privacy policy", privacyIntro: "This policy explains, in general terms, what information LendUp needs to operate and how it relates to loans completed through the platform." },
    notFound: { title: "This page is unavailable", text: "The link may have changed or the page may no longer exist.", button: "Back to home" }
  }
};
