window.LENDUP_TRANSLATIONS = {
  es: {
    a11y: { skip: "Saltar al contenido principal" },
    lang: { toggle: "Cambiar idioma", switchToEnglish: "Cambiar idioma a inglés", switchToSpanish: "Cambiar idioma a español" },
    nav: { brand: "LendUp - Inicio", label: "Navegación principal", open: "Abrir menú", close: "Cerrar menú", home: "Inicio", benefits: "Beneficios", how: "Cómo funciona", safety: "Seguridad", about: "Nosotros", faq: "FAQ" },
    actions: { exploreLendUp: "Comenzar aquí", seeHow: "Ver cómo funciona", explore: "Buscar objetos", publish: "Publicar un objeto" },
    status: { available: "Disponible" },
    hero: {
      carouselLabel: "Propuestas principales de LendUp", slide1Label: "1 de 3: propuesta general", slide2Label: "2 de 3: para prestatarios", slide3Label: "3 de 3: para prestamistas",
      previous: "Mostrar slide anterior", next: "Mostrar slide siguiente", indicators: "Seleccionar slide", goTo1: "Ir al slide 1", goTo2: "Ir al slide 2", goTo3: "Ir al slide 3",
      slide1Eyebrow: "Préstamos entre estudiantes universitarios", slide1Title: "Presta lo que no usas.<br><span>Consigue lo que necesitas.</span>", slide1Text: "Encuentra y presta objetos dentro de tu comunidad universitaria, con estudiantes verificados, condiciones claras y respaldo durante todo el préstamo.",
      slide2Eyebrow: "Para quienes necesitan un objeto", slide2Title: "Consigue lo que necesitas sin comprarlo para usarlo una sola vez.", slide2Text: "Busca objetos disponibles, revisa sus condiciones y solicita el periodo que necesitas dentro de tu comunidad universitaria.",
      slide3Eyebrow: "Para quienes tienen algo que prestar", slide3Title: "Dale utilidad a los objetos que hoy permanecen guardados.", slide3Text: "Publica tus objetos, define su disponibilidad y condiciones, revisa solicitudes y gestiona cada préstamo desde la entrega hasta la devolución.",
      trustLabel: "Señales de confianza", trust1: "Estudiantes verificados", trust2: "Condiciones registradas", trust3: "Evidencias del objeto",
      visual1Label: "Vista previa del catálogo de LendUp", visual2Label: "Objetos disponibles en LendUp", visual3Label: "Vista previa de publicación de un objeto", search: "Buscar objetos", verified: "Estudiante verificado", visibleReputation: "Reputación visible", recordedTerms: "Condiciones registradas",
      newListing: "Nueva publicación", defineDetails: "Define los detalles del objeto", availability: "Disponibilidad", fee: "Tarifa", deposit: "Garantía", conditions: "Condiciones", youDecide: "Tú decides cuándo", youDefine: "Definida por ti", recorded: "Queda registrada", clearBefore: "Claras antes de aceptar", readyToPublish: "Listo para publicar"
    },
    benefits: {
      eyebrow: "¿Por qué LendUp?", title: "Más claridad y respaldo en cada préstamo", subtitle: "Busca, acuerda condiciones y registra cada etapa en un solo lugar.", sliderLabel: "Beneficios de LendUp", controlsLabel: "Seleccionar beneficio",
      card1Title: "Encuentra lo que necesitas", card1Text: "Busca objetos y revisa disponibilidad, ubicación y condiciones antes de enviar una solicitud.",
      card2Title: "Conoce a la otra persona", card2Text: "Consulta su verificación universitaria y reputación antes de aceptar o enviar una solicitud.",
      card3Title: "Acuerdos claros desde el inicio", card3Text: "La tarifa, la garantía, las fechas y las condiciones quedan registradas para cada reserva.",
      card4Title: "Respaldo hasta la devolución", card4Text: "Evidencias, notificaciones, recordatorios e incidencias ayudan a mantener el préstamo trazable hasta su cierre."
    },
    roles: {
      eyebrow: "Dos formas de participar", title: "Encuentra tu lugar en la comunidad LendUp",
      borrowerEyebrow: "Necesito un objeto", borrowerTitle: "Encuentra lo que necesitas temporalmente.", borrowerText: "Accede a objetos de otros estudiantes cuando solo los necesitas por un periodo determinado.", borrowerPoint1: "Revisa disponibilidad y condiciones.", borrowerPoint2: "Coordina una operación dentro de LendUp.",
      lenderEyebrow: "Tengo algo para prestar", lenderTitle: "Dale utilidad a los objetos que no estás usando.", lenderText: "Pon tus objetos disponibles para otros estudiantes y mantén control sobre cuándo y bajo qué condiciones los prestas.", lenderPoint1: "Define disponibilidad y condiciones.", lenderPoint2: "Gestiona tus operaciones desde LendUp."
    },
    catalog: {
      eyebrow: "Explora posibilidades", title: "Objetos para tu vida universitaria", subtitle: "Cámaras, libros y herramientas: ejemplos de objetos para tus clases, proyectos y actividades universitarias.", cameraCategory: "Cámaras", cameraName: "Cámara Canon", calculatorCategory: "Calculadoras", calculatorName: "Calculadora científica", booksCategory: "Libros", booksName: "Libros académicos", techCategory: "Tecnología", tabletName: "Tablet para estudiar", toolsCategory: "Herramientas", toolsName: "Kit de herramientas", visualRate: "Tarifa definida por el prestamista"
    },
    how: {
      eyebrow: "Cómo funciona", title: "Un proceso claro para ambos lados", subtitle: "Elige tu rol y conoce cada etapa del préstamo.", tabLabel: "Selecciona tu rol", borrowerTab: "Buscar", lenderTab: "Prestar",
      borrowerSteps: [
        ["Crea y verifica tu cuenta", "Regístrate con tu información universitaria y completa la verificación correspondiente."],
        ["Busca y solicita", "Encuentra el objeto que necesitas, revisa disponibilidad y condiciones, y envía una solicitud."],
        ["Recibe con respaldo", "Completa los pasos de la reserva y registra evidencias al recibir el objeto."],
        ["Devuelve y califica", "Entrega el objeto según lo acordado y registra tu experiencia."]
      ],
      lenderSteps: [
        ["Publica y define condiciones", "Registra el objeto, su disponibilidad, tarifa, garantía y condiciones."],
        ["Revisa solicitudes", "Consulta al estudiante interesado y decide si aceptas la solicitud."],
        ["Entrega con evidencias", "Registra el estado del objeto y confirma la entrega."],
        ["Confirma la devolución", "Revisa el estado final, completa el préstamo y califica al prestatario."]
      ]
    },
    video: { title: "About the Product", text: "Conoce la propuesta y el funcionamiento general de LendUp.", iframeTitle: "Video sobre el producto LendUp" },
    safety: {
      eyebrow: "Seguridad y confianza", title: "Confianza en cada etapa del préstamo", subtitle: "LendUp registra información relevante de la operación para que ambas partes tengan mayor claridad antes, durante y después del préstamo.", financialNote: "Tu información financiera sensible no se almacena directamente en LendUp. Las operaciones económicas se procesan mediante un proveedor externo y con los medios que este habilite.",
      item1Title: "Verificación universitaria", item1Text: "Conoce la condición de estudiante antes de operar.", item2Title: "Condiciones registradas", item2Text: "Lo acordado en una reserva permanece registrado para esa operación.", item3Title: "Pagos y garantías", item3Text: "Un proveedor externo procesa la tarifa del préstamo y, cuando corresponda, la garantía monetaria con sus medios habilitados.", item4Title: "Evidencias del objeto", item4Text: "Las evidencias registran cómo se entrega y cómo se devuelve el objeto.", item5Title: "Gestión de incidencias", item5Text: "Reporta una situación y conserva el contexto de la operación.", item6Title: "Reputación entre estudiantes", item6Text: "Las valoraciones ayudan a tomar mejores decisiones futuras.",
      flowLabel: "Flujo económico de una reserva", flow1: "Se confirma la reserva", flow2: "Se procesa antes de la entrega", flow3: "Se confirma la recepción", flow4: "Se solicita la liberación de la tarifa"
    },
    commission: { eyebrow: "Modelo por operación", title: "Una comisión clara dentro de cada préstamo", text1: "LendUp obtiene ingresos mediante una comisión asociada a cada operación de préstamo. Antes de realizar el pago, el prestatario puede revisar el desglose económico de la operación.", text2: "La tarifa del préstamo, la comisión de LendUp, el costo del proveedor de pago cuando corresponda, la garantía monetaria y el monto total se muestran por separado." },
    about: { eyebrow: "Sobre nosotros", title: "Construido para la comunidad universitaria", subtitle: "LendUp nace para convertir el préstamo informal de objetos en una experiencia más clara, práctica y respaldada.", missionTitle: "Misión", missionText: "Facilitar que los estudiantes accedan a los objetos que necesitan para su vida académica prestándose objetos entre sí, con procesos claros de disponibilidad, garantía, entrega y devolución que generan confianza y reducen el gasto innecesario en compras de uso esporádico.", visionTitle: "Visión", visionText: "Ser la plataforma de referencia para el préstamo de objetos entre estudiantes en las universidades del Perú, reconocida por construir una comunidad de confianza sostenida en la reputación y el uso responsable de los recursos compartidos." },
    team: { eyebrow: "Equipo", title: "Las personas detrás de LendUp" },
    faq: {
      eyebrow: "Preguntas frecuentes", title: "Lo importante, explicado con claridad", subtitle: "Respuestas breves sobre publicaciones, reservas, pagos, devoluciones y garantías.",
      items: [
        ["¿Puede cambiar una publicación después de que reservé?", "Puede cambiar para futuras solicitudes. Si la reserva ya fue confirmada, sus condiciones quedan registradas y no cambian por modificaciones posteriores."],
        ["¿Notificaciones y recordatorios son lo mismo?", "No. Las notificaciones informan eventos que ya ocurrieron; los recordatorios anticipan fechas o acciones programadas."],
        ["¿Cómo se procesan los pagos y garantías?", "Un proveedor externo procesa estas operaciones. LendUp registra el estado necesario, pero no almacena directamente la información financiera sensible completa."],
        ["¿Cuándo recibe el prestamista la tarifa?", "El prestatario procesa la tarifa del préstamo después de confirmarse la reserva y antes de la entrega. La liberación al prestamista se solicita después de que el prestatario confirma que recibió el objeto y el préstamo queda activo."],
        ["¿Puedo cancelar una reserva?", "Sí. Una reserva confirmada puede cancelarse antes de la entrega del objeto. El periodo reservado se libera y los reembolsos o devoluciones correspondientes se gestionan según las condiciones previamente aceptadas."],
        ["¿Puedo solicitar más tiempo para devolver el objeto?", "El prestatario puede solicitar una extensión antes del vencimiento. El prestamista decide si la acepta o rechaza y, cuando la extensión genere un costo adicional, este se procesa antes de actualizar la nueva fecha."],
        ["¿Qué ocurre con la garantía si se reporta una incidencia?", "La garantía permanece pendiente mientras se revisa la incidencia. Si la resolución determina una afectación parcial o total, se aplica únicamente el monto correspondiente y se devuelve el saldo restante."],
        ["¿Cuándo se devuelve la garantía?", "Cuando el préstamo finaliza correctamente y no existen incidencias pendientes, LendUp solicita al proveedor externo la devolución de la garantía monetaria."]
      ]
    },
    cta: { eyebrow: "Comunidad LendUp", title: "Tu próximo préstamo puede empezar aquí.", text: "Encuentra lo que necesitas o dale utilidad a aquello que no estás usando dentro de tu comunidad universitaria.", publishPrompt: "¿Tienes algo para prestar? Publica un objeto" },
    footer: { tagline: "Presta lo que no usas. Consigue lo que necesitas.", description: "Préstamos temporales de objetos entre estudiantes universitarios, con procesos más claros y respaldados.", explore: "Explora", legal: "Legal", follow: "Síguenos", terms: "Términos y condiciones", privacy: "Política de privacidad", rights: "Todos los derechos reservados." },
    social: { github: "GitHub de LendUp", youtube: "YouTube de LendUp", instagram: "Instagram de LendUp", linkedin: "LinkedIn de LendUp" },
    legal: { back: "Volver al inicio", updated: "Última actualización: octubre de 2026", termsTitle: "Términos y condiciones", termsIntro: "Estas condiciones describen de forma general el uso de LendUp y las responsabilidades básicas de quienes prestan o solicitan objetos.", privacyTitle: "Política de privacidad", privacyIntro: "Esta política explica, en términos generales, qué información necesita LendUp para operar y cómo se relaciona con los préstamos realizados en la plataforma." },
    notFound: { title: "Esta página no está disponible", text: "El enlace puede haber cambiado o la página ya no existe.", button: "Volver al inicio" }
  },
  en: {
    a11y: { skip: "Skip to main content" },
    lang: { toggle: "Change language", switchToEnglish: "Switch language to English", switchToSpanish: "Switch language to Spanish" },
    nav: { brand: "LendUp - Home", label: "Primary navigation", open: "Open menu", close: "Close menu", home: "Home", benefits: "Benefits", how: "How it works", safety: "Safety", about: "About us", faq: "FAQ" },
    actions: { exploreLendUp: "Get started", seeHow: "See how it works", explore: "Find items", publish: "List an item" },
    status: { available: "Available" },
    hero: {
      carouselLabel: "Main LendUp propositions", slide1Label: "1 of 3: general proposition", slide2Label: "2 of 3: for borrowers", slide3Label: "3 of 3: for lenders", previous: "Show previous slide", next: "Show next slide", indicators: "Select a slide", goTo1: "Go to slide 1", goTo2: "Go to slide 2", goTo3: "Go to slide 3",
      slide1Eyebrow: "Peer-to-peer lending for university students", slide1Title: "Lend what you don't use.<br><span>Get what you need.</span>", slide1Text: "Find and lend items within your university community, with verified students, clear terms, and support throughout every loan.",
      slide2Eyebrow: "For students who need an item", slide2Title: "Get what you need without buying it for one-time use.", slide2Text: "Find available items, review their terms, and request the period you need within your university community.",
      slide3Eyebrow: "For students with something to lend", slide3Title: "Put the items sitting in storage to good use.", slide3Text: "List your items, set their availability and terms, review requests, and manage each loan from handoff to return.",
      trustLabel: "Trust signals", trust1: "Verified students", trust2: "Recorded terms", trust3: "Item evidence", visual1Label: "Preview of the LendUp catalog", visual2Label: "Items available on LendUp", visual3Label: "Preview of an item listing", search: "Search items", verified: "Verified student", visibleReputation: "Visible reputation", recordedTerms: "Recorded terms", newListing: "New listing", defineDetails: "Set the item's details", availability: "Availability", fee: "Fee", deposit: "Deposit", conditions: "Terms", youDecide: "You choose when", youDefine: "Set by you", recorded: "Recorded for the loan", clearBefore: "Clear before accepting", readyToPublish: "Ready to list"
    },
    benefits: {
      eyebrow: "Why LendUp?", title: "More clarity and support in every loan", subtitle: "Find items, agree on terms, and record every stage in one place.", sliderLabel: "LendUp benefits", controlsLabel: "Select a benefit",
      card1Title: "Find what you need", card1Text: "Search for items and check availability, location, and terms before sending a request.", card2Title: "Get to know the other person", card2Text: "Check their university verification and reputation before accepting or sending a request.", card3Title: "Clear agreements from the start", card3Text: "The fee, deposit, dates, and terms are recorded for each booking.", card4Title: "Support through to the return", card4Text: "Evidence, notifications, reminders, and issue reports help keep the loan traceable through to completion."
    },
    roles: {
      eyebrow: "Two ways to take part", title: "Find your place in the LendUp community", borrowerEyebrow: "I need an item", borrowerTitle: "Find what you need temporarily.", borrowerText: "Access items from other students when you only need them for a limited period.", borrowerPoint1: "Review availability and terms.", borrowerPoint2: "Coordinate a transaction through LendUp.", lenderEyebrow: "I have something to lend", lenderTitle: "Put the items you aren't using to good use.", lenderText: "Make your items available to other students while staying in control of when and under what terms you lend them.", lenderPoint1: "Set availability and terms.", lenderPoint2: "Manage your transactions through LendUp."
    },
    catalog: { eyebrow: "Explore the possibilities", title: "Items for university life", subtitle: "Cameras, books and tools: examples of items for your classes, projects and university activities.", cameraCategory: "Cameras", cameraName: "Canon camera", calculatorCategory: "Calculators", calculatorName: "Scientific calculator", booksCategory: "Books", booksName: "Academic books", techCategory: "Technology", tabletName: "Study tablet", toolsCategory: "Tools", toolsName: "Tool kit", visualRate: "Fee set by the lender" },
    how: {
      eyebrow: "How it works", title: "A clear process for both sides", subtitle: "Choose your role and see every stage of a loan.", tabLabel: "Select your role", borrowerTab: "Find", lenderTab: "Lend",
      borrowerSteps: [["Create and verify your account", "Register with your university information and complete the relevant verification."], ["Find and request", "Find the item you need, review availability and terms, and send a request."], ["Receive with support", "Complete the booking steps and record evidence when you receive the item."], ["Return and review", "Return the item as agreed and record your experience."]],
      lenderSteps: [["List and set terms", "Record the item, its availability, fee, deposit, and terms."], ["Review requests", "Review the interested student and decide whether to accept the request."], ["Hand off with evidence", "Record the item's condition and confirm the handoff."], ["Confirm the return", "Review the final condition, complete the loan, and review the borrower."]]
    },
    video: { title: "About the Product", text: "Learn about LendUp's proposition and overall experience.", iframeTitle: "About the LendUp product" },
    safety: {
      eyebrow: "Safety and trust", title: "Confidence at every stage of the loan", subtitle: "LendUp records relevant transaction details so both parties have greater clarity before, during, and after the loan.", financialNote: "Your sensitive financial information is not stored directly by LendUp. Financial transactions are processed by an external provider using its enabled payment methods.", item1Title: "University verification", item1Text: "Check student status before transacting.", item2Title: "Recorded terms", item2Text: "The terms agreed in a booking remain recorded for that transaction.", item3Title: "Payments and deposits", item3Text: "An external provider processes the loan fee and, where applicable, the monetary deposit using its enabled methods.", item4Title: "Item evidence", item4Text: "Evidence records the item's condition at handoff and return.", item5Title: "Issue management", item5Text: "Report an issue while preserving the transaction context.", item6Title: "Student reputation", item6Text: "Reviews help the community make better future decisions.", flowLabel: "Booking payment flow", flow1: "The booking is confirmed", flow2: "Payment is processed before handoff", flow3: "Receipt is confirmed", flow4: "Fee release is requested"
    },
    commission: { eyebrow: "Per-transaction model", title: "A clear commission within each loan", text1: "LendUp earns revenue through a commission associated with each loan transaction. Before paying, the borrower can review the financial breakdown of the transaction.", text2: "The loan fee, LendUp commission, payment provider charge where applicable, monetary deposit, and total amount are shown separately." },
    about: { eyebrow: "About us", title: "Built for the university community", subtitle: "LendUp was created to turn informal item lending into a clearer, more practical, and better-supported experience.", missionTitle: "Mission", missionText: "Help students access the items they need for academic life by lending items to one another, with clear availability, deposit, handoff, and return processes that build trust and reduce unnecessary spending on purchases for occasional use.", visionTitle: "Vision", visionText: "Be the leading platform for item lending among students at universities in Peru, recognized for building a trusted community grounded in reputation and the responsible use of shared resources." },
    team: { eyebrow: "Team", title: "The people behind LendUp" },
    faq: {
      eyebrow: "Frequently asked questions", title: "The important details, clearly explained", subtitle: "Short answers about listings, bookings, payments, returns, and deposits.",
      items: [["Can a listing change after I book?", "It can change for future requests. Once a booking is confirmed, its recorded terms are not affected by later updates."], ["Are notifications and reminders the same?", "No. Notifications report events that already happened; reminders anticipate scheduled dates or actions."], ["How are payments and deposits processed?", "An external provider processes these transactions. LendUp records the required status but does not directly store complete sensitive financial information."], ["When does the lender receive the fee?", "The borrower pays the loan fee after the booking is confirmed and before handoff. Release to the lender is requested after the borrower confirms receipt and the loan becomes active."], ["Can I cancel a booking?", "Yes. A confirmed booking can be canceled before the item is handed over. The reserved period becomes available again, and any applicable refunds or returns of funds are handled according to the previously accepted terms."], ["Can I request more time to return the item?", "The borrower can request an extension before the due date. The lender decides whether to accept or reject it. If the extension adds a charge, payment is processed before the new date is recorded."], ["What happens to the deposit if an issue is reported?", "The deposit remains pending while the issue is reviewed. If the resolution determines that some or all of it must be applied, only the corresponding amount is used and the remaining balance is returned."], ["When is the deposit returned?", "When the loan ends successfully and there are no pending issues, LendUp asks the external provider to return the monetary deposit."]]
    },
    cta: { eyebrow: "LendUp community", title: "Your next loan can start here.", text: "Find what you need or put the items you aren't using to work within your university community.", publishPrompt: "Do you have something to lend? List an item" },
    footer: { tagline: "Lend what you don't use. Get what you need.", description: "Temporary item lending between university students, with clearer and better-supported processes.", explore: "Explore", legal: "Legal", follow: "Follow Us", terms: "Terms and conditions", privacy: "Privacy policy", rights: "All rights reserved." },
    social: { github: "LendUp on GitHub", youtube: "LendUp on YouTube", instagram: "LendUp on Instagram", linkedin: "LendUp on LinkedIn" },
    legal: { back: "Back to home", updated: "Last updated: October 2026", termsTitle: "Terms and conditions", termsIntro: "These terms provide a general description of LendUp usage and the basic responsibilities of people who lend or request items.", privacyTitle: "Privacy policy", privacyIntro: "This policy explains, in general terms, what information LendUp needs to operate and how it relates to loans completed through the platform." },
    notFound: { title: "This page is unavailable", text: "The link may have changed or the page may no longer exist.", button: "Back to home" }
  }
};
